const { PrismaClient, UserRole, ConsultationType, Disponibilite, ModeReglement, StatutConventionnement } = require('@prisma/client')
const { hash } = require('bcrypt')

const prisma = new PrismaClient()

async function main() {
  const password = await hash('password123', 10)

  const professionnels = [
    {
      email: 'hulk@avengers.med',
      password,
      prenom: 'Bruce',
      nom: 'Banner',
      telephone: '0666666666',
      photo_url: '/img/professionel/Hulk.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Radiologie',
      sous_specialite: 'Exposition aux rayons gamma',
      diplomes_urls: ['harvard.pdf', 'gamma-research.pdf'],
      numero_adeli: '123456789',
      numero_rpps: '12345678901',
      consultation_type: [ConsultationType.PRESENTIEL],
      tarif_consultation: 150.00,
      statut_conventionnement: StatutConventionnement.SECTEUR_2,
      modes_reglement: [ModeReglement.CB, ModeReglement.VIREMENT],
      carte_vitale: true,
      description: "Spécialiste en radiologie et expert en rayons gamma. Peut avoir des accès de colère pendant les consultations. Merci de ne pas contrarier le médecin.",
      experience_annees: 15,
      langues_parlees: ['Français', 'Anglais', 'Hulk'],
      horaire_ouverture: '09:00',
      horaire_fermeture: '17:00',
      duree_consultation: 30,
      jours_travail: ['LUNDI', 'MERCREDI', 'VENDREDI'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 7,
      adresse_rue: '177A Bleecker Street',
      ville: 'New York',
      code_postal: '10012',
      pays: 'USA',
      acces_pmr: true,
      parking: true,
      equipements: ['Scanner gamma', 'Salle de décompression', 'Murs renforcés'],
      accepte_urgences: true,
      taux_remplissage: 0.8
    },
    {
      email: 'chopper@sunny.med',
      password,
      prenom: 'Tony Tony',
      nom: 'Chopper',
      telephone: '0677777777',
      photo_url: '/img/professionel/chopper.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Médecine générale',
      sous_specialite: 'Médecine d\'aventure',
      diplomes_urls: ['drum-kingdom-university.pdf'],
      numero_adeli: '987654321',
      numero_rpps: '98765432101',
      consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.VISIO],
      tarif_consultation: 80.00,
      statut_conventionnement: StatutConventionnement.SECTEUR_1,
      modes_reglement: [ModeReglement.CB, ModeReglement.ESPECES, ModeReglement.TIERS_PAYANT],
      carte_vitale: true,
      description: "Médecin polyvalent spécialisé dans les soins d'urgence en mer. Accepte les patients de toutes espèces. N'est pas un tanuki.",
      experience_annees: 5,
      langues_parlees: ['Français', 'Anglais', 'Animal'],
      horaire_ouverture: '08:00',
      horaire_fermeture: '20:00',
      duree_consultation: 20,
      jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 1,
      adresse_rue: 'Thousand Sunny',
      ville: 'Grand Line',
      code_postal: '00001',
      pays: 'Seas',
      acces_pmr: true,
      parking: false,
      equipements: ['Rumble Balls', 'Cabinet mobile', 'Herbes médicinales'],
      accepte_urgences: true,
      taux_remplissage: 0.9
    },
    {
      email: 'orihime@karakura.med',
      password,
      prenom: 'Orihime',
      nom: 'Inoue',
      telephone: '0688888888',
      photo_url: '/img/professionel/orihime.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Médecine régénérative',
      sous_specialite: 'Soins spirituels',
      diplomes_urls: ['karakura-healing.pdf'],
      numero_adeli: '456789123',
      numero_rpps: '45678912301',
      consultation_type: [ConsultationType.PRESENTIEL],
      tarif_consultation: 95.00,
      statut_conventionnement: StatutConventionnement.SECTEUR_1,
      modes_reglement: [ModeReglement.CB],
      carte_vitale: true,
      description: "Spécialiste en soins régénératifs instantanés. Utilise une approche holistique avec ses Shun Shun Rikka. Propose des plats originaux pendant la convalescence.",
      experience_annees: 3,
      langues_parlees: ['Français', 'Japonais'],
      horaire_ouverture: '10:00',
      horaire_fermeture: '18:00',
      duree_consultation: 45,
      jours_travail: ['MARDI', 'JEUDI', 'SAMEDI'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 2,
      adresse_rue: '2-15-1 Karakura',
      ville: 'Tokyo',
      code_postal: '162-0845',
      pays: 'Japon',
      acces_pmr: true,
      parking: true,
      equipements: ['Barrière spirituelle', 'Salle de méditation', 'Cuisine expérimentale'],
      accepte_urgences: true,
      taux_remplissage: 0.7
    },
    {
      email: 'recovery@ua.med',
      password,
      prenom: 'Chiyo',
      nom: 'Shuzenji',
      telephone: '0699999999',
      photo_url: '/img/professionel/recovery-girl.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Pédiatrie',
      sous_specialite: 'Traumatologie des super-héros',
      diplomes_urls: ['ua-medical.pdf', 'hero-medicine.pdf'],
      numero_adeli: '789123456',
      numero_rpps: '78912345601',
      consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.HYBRIDE],
      tarif_consultation: 120.00,
      statut_conventionnement: StatutConventionnement.SECTEUR_2,
      modes_reglement: [ModeReglement.CB, ModeReglement.TIERS_PAYANT],
      carte_vitale: true,
      description: "Infirmière scolaire spécialisée dans les soins aux jeunes héros. Attention : les soins peuvent épuiser le patient.",
      experience_annees: 40,
      langues_parlees: ['Français', 'Japonais', 'Anglais'],
      horaire_ouverture: '07:00',
      horaire_fermeture: '19:00',
      duree_consultation: 15,
      jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 0,
      adresse_rue: 'UA High School',
      ville: 'Musutafu',
      code_postal: '321-654',
      pays: 'Japon',
      acces_pmr: true,
      parking: true,
      equipements: ['Lits de récupération', 'Stock de bonbons', 'Défibrillateur Plus Ultra'],
      accepte_urgences: true,
      taux_remplissage: 1.0
    },
    {
      email: 'saitama@hero.med',
      password,
      prenom: 'Saitama',
      nom: 'Sensei',
      telephone: '0611111111',
      photo_url: '/img/professionel/saitama.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Préparation physique',
      sous_specialite: 'Renforcement musculaire extrême',
      diplomes_urls: ['self-training.pdf'],
      numero_adeli: '321654987',
      numero_rpps: '32165498701',
      consultation_type: [ConsultationType.PRESENTIEL],
      tarif_consultation: 50.00,
      statut_conventionnement: StatutConventionnement.NON_CONVENTIONNE,
      modes_reglement: [ModeReglement.ESPECES],
      carte_vitale: false,
      description: "Coach sportif minimaliste. Programme : 100 pompes, 100 squats, 100 abdos et 10km de course. TOUS LES JOURS !",
      experience_annees: 3,
      langues_parlees: ['Français', 'Japonais'],
      horaire_ouverture: '14:00',
      horaire_fermeture: '17:00',
      duree_consultation: 60,
      jours_travail: ['SAMEDI', 'DIMANCHE'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 30,
      adresse_rue: 'Z-City, Apt 666',
      ville: 'Z-City',
      code_postal: '666-666',
      pays: 'Japon',
      acces_pmr: false,
      parking: false,
      equipements: ['Zone d\'entraînement', 'Climatisation cassée', 'Manga'],
      accepte_urgences: false,
      taux_remplissage: 0.2
    },
    {
      email: 'sanji@baratie.med',
      password,
      prenom: 'Sanji',
      nom: 'Vinsmoke',
      telephone: '0622222222',
      photo_url: '/img/professionel/sanji.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Nutrition',
      sous_specialite: 'Cuisine thérapeutique',
      diplomes_urls: ['baratie-culinary.pdf', 'all-blue-research.pdf'],
      numero_adeli: '147258369',
      numero_rpps: '14725836901',
      consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.VISIO],
      tarif_consultation: 90.00,
      statut_conventionnement: StatutConventionnement.SECTEUR_1,
      modes_reglement: [ModeReglement.CB, ModeReglement.ESPECES],
      carte_vitale: true,
      description: "Expert en nutrition et cuisine thérapeutique. Attention : comportement différent selon le genre du patient.",
      experience_annees: 10,
      langues_parlees: ['Français', 'Anglais', 'Love'],
      horaire_ouverture: '11:00',
      horaire_fermeture: '23:00',
      duree_consultation: 40,
      jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 3,
      adresse_rue: 'Baratie Restaurant',
      ville: 'East Blue',
      code_postal: '11111',
      pays: 'Seas',
      acces_pmr: true,
      parking: false,
      equipements: ['Cuisine professionnelle', 'Jardin d\'herbes', 'Cave à vin médicinale'],
      accepte_urgences: true,
      taux_remplissage: 0.95
    },
    {
      email: 'tsunade@konoha.med',
      password,
      prenom: 'Tsunade',
      nom: 'Senju',
      telephone: '0633333333',
      photo_url: '/img/professionel/tsunade.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Chirurgie',
      sous_specialite: 'Ninjutsu médical',
      diplomes_urls: ['konoha-medical.pdf', 'hokage-certificate.pdf'],
      numero_adeli: '258369147',
      numero_rpps: '25836914701',
      consultation_type: [ConsultationType.PRESENTIEL],
      tarif_consultation: 200.00,
      statut_conventionnement: StatutConventionnement.SECTEUR_2,
      modes_reglement: [ModeReglement.CB, ModeReglement.ESPECES],
      carte_vitale: true,
      description: "Chirurgienne de génie et experte en médecine ninja. Possibilité de paris pendant la consultation (non remboursés).",
      experience_annees: 50,
      langues_parlees: ['Français', 'Japonais', 'Ninja'],
      horaire_ouverture: '10:00',
      horaire_fermeture: '16:00',
      duree_consultation: 30,
      jours_travail: ['LUNDI', 'MERCREDI', 'VENDREDI'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 14,
      adresse_rue: 'Tour de l\'Hokage',
      ville: 'Konoha',
      code_postal: '12345',
      pays: 'Pays du Feu',
      acces_pmr: true,
      parking: true,
      equipements: ['Bloc opératoire', 'Salle de régénération', 'Machine à sous'],
      accepte_urgences: true,
      taux_remplissage: 0.6
    },
    {
      email: 'zeno@dragon.med',
      password,
      prenom: 'Zeno',
      nom: 'Sama',
      telephone: '0644444444',
      photo_url: '/img/professionel/zeno.jpg',
      role: UserRole.MEDECIN,
      specialisation: 'Médecine universelle',
      sous_specialite: 'Manipulation temporelle',
      diplomes_urls: ['universe-7.pdf', 'all-universes.pdf'],
      numero_adeli: '369147258',
      numero_rpps: '36914725801',
      consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.VISIO, ConsultationType.HYBRIDE],
      tarif_consultation: 1000.00,
      statut_conventionnement: StatutConventionnement.NON_CONVENTIONNE,
      modes_reglement: [ModeReglement.CB],
      carte_vitale: false,
      description: "Médecin omnipotent. Peut effacer l'univers en cas d'insatisfaction. Consultation sur recommandation divine uniquement.",
      experience_annees: 1000000,
      langues_parlees: ['Toutes'],
      horaire_ouverture: '00:00',
      horaire_fermeture: '23:59',
      duree_consultation: 1,
      jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI', 'DIMANCHE'],
      disponibilite: Disponibilite.DISPONIBLE,
      delai_rdv_moyen: 365,
      adresse_rue: 'Palais de Zeno',
      ville: 'Au-delà',
      code_postal: '00000',
      pays: 'Multivers',
      acces_pmr: true,
      parking: true,
      equipements: ['Bouton de destruction universelle', 'Salle temporelle', 'Gardes divins'],
      accepte_urgences: false,
      taux_remplissage: 0.1
    }
  ]

  for (const professionnel of professionnels) {
    await prisma.user.create({
      data: professionnel
    })
  }
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
