import { PrismaClient, UserRole, ConsultationType, Disponibilite, ModeReglement, StatutConventionnement, NutritionalStatus, ProgressionStatus } from '@prisma/client';
import { hash } from 'bcrypt';

const prisma = new PrismaClient();

const professionnels = [
  {
    email: 'hulk@avengers.med',
    password: await hash('password123', 10),
    prenom: 'Bruce',
    nom: 'Banner',
    telephone: '0666666666',
    photo_url: '/img/professionel/Hulk.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Radiologie',
    sous_specialite: 'Exposition aux rayons gamma',
    diplomes_urls: ['harvard.pdf', 'gamma-research.pdf'],
    numero_adeli: '123456789',
    numero_rpps: '12345678901',
    consultation_type: [ConsultationType.PRESENTIEL],
    tarif_consultation: 150.00,
    statut_conventionnement: StatutConventionnement.SECTEUR_2,
    modes_reglement: [ModeReglement.CB, ModeReglement.VIREMENT],
    carte_vitale: true,
    description: "Spécialiste en radiologie et expert en rayons gamma. Peut avoir des accès de colère pendant les consultations. Merci de ne pas contrarier le médecin.",
    experience_annees: 15,
    langues_parlees: ['Français', 'Anglais', 'Hulk'],
    horaire_ouverture: '09:00',
    horaire_fermeture: '17:00',
    duree_consultation: 30,
    jours_travail: ['LUNDI', 'MERCREDI', 'VENDREDI'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 7,
    adresse_rue: '177A Bleecker Street',
    ville: 'New York',
    code_postal: '10012',
    pays: 'USA',
    acces_pmr: true,
    parking: true,
    equipements: ['Scanner gamma', 'Salle de décompression', 'Murs renforcés'],
    accepte_urgences: true,
    taux_remplissage: 0.8
  },
  {
    email: 'chopper@sunny.med',
    password: await hash('password123', 10),
    prenom: 'Tony Tony',
    nom: 'Chopper',
    telephone: '0677777777',
    photo_url: '/img/professionel/chopper.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Médecine générale',
    sous_specialite: 'Médecine d\'aventure',
    diplomes_urls: ['drum-kingdom-university.pdf'],
    numero_adeli: '987654321',
    numero_rpps: '98765432101',
    consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.VISIO],
    tarif_consultation: 80.00,
    statut_conventionnement: StatutConventionnement.SECTEUR_1,
    modes_reglement: [ModeReglement.CB, ModeReglement.ESPECES, ModeReglement.TIERS_PAYANT],
    carte_vitale: true,
    description: "Médecin polyvalent spécialisé dans les soins d'urgence en mer. Accepte les patients de toutes espèces. N'est pas un tanuki.",
    experience_annees: 5,
    langues_parlees: ['Français', 'Anglais', 'Animal'],
    horaire_ouverture: '08:00',
    horaire_fermeture: '20:00',
    duree_consultation: 20,
    jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 1,
    adresse_rue: 'Thousand Sunny',
    ville: 'Grand Line',
    code_postal: '00001',
    pays: 'Seas',
    acces_pmr: true,
    parking: false,
    equipements: ['Rumble Balls', 'Cabinet mobile', 'Herbes médicinales'],
    accepte_urgences: true,
    taux_remplissage: 0.9
  },
  {
    email: 'orihime@karakura.med',
    password: await hash('password123', 10),
    prenom: 'Orihime',
    nom: 'Inoue',
    telephone: '0688888888',
    photo_url: '/img/professionel/orihime.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Médecine régénérative',
    sous_specialite: 'Soins spirituels',
    diplomes_urls: ['karakura-healing.pdf'],
    numero_adeli: '456789123',
    numero_rpps: '45678912301',
    consultation_type: [ConsultationType.PRESENTIEL],
    tarif_consultation: 95.00,
    statut_conventionnement: StatutConventionnement.SECTEUR_1,
    modes_reglement: [ModeReglement.CB],
    carte_vitale: true,
    description: "Spécialiste en soins régénératifs instantanés. Utilise une approche holistique avec ses Shun Shun Rikka. Propose des plats originaux pendant la convalescence.",
    experience_annees: 3,
    langues_parlees: ['Français', 'Japonais'],
    horaire_ouverture: '10:00',
    horaire_fermeture: '18:00',
    duree_consultation: 45,
    jours_travail: ['MARDI', 'JEUDI', 'SAMEDI'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 2,
    adresse_rue: '2-15-1 Karakura',
    ville: 'Tokyo',
    code_postal: '162-0845',
    pays: 'Japon',
    acces_pmr: true,
    parking: true,
    equipements: ['Barrière spirituelle', 'Salle de méditation', 'Cuisine expérimentale'],
    accepte_urgences: true,
    taux_remplissage: 0.7
  },
  {
    email: 'recovery@ua.med',
    password: await hash('password123', 10),
    prenom: 'Chiyo',
    nom: 'Shuzenji',
    telephone: '0699999999',
    photo_url: '/img/professionel/recovery-girl.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Pédiatrie',
    sous_specialite: 'Traumatologie des super-héros',
    diplomes_urls: ['ua-medical.pdf', 'hero-medicine.pdf'],
    numero_adeli: '789123456',
    numero_rpps: '78912345601',
    consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.HYBRIDE],
    tarif_consultation: 120.00,
    statut_conventionnement: StatutConventionnement.SECTEUR_2,
    modes_reglement: [ModeReglement.CB, ModeReglement.TIERS_PAYANT],
    carte_vitale: true,
    description: "Infirmière scolaire spécialisée dans les soins aux jeunes héros. Attention : les soins peuvent épuiser le patient.",
    experience_annees: 40,
    langues_parlees: ['Français', 'Japonais', 'Anglais'],
    horaire_ouverture: '07:00',
    horaire_fermeture: '19:00',
    duree_consultation: 15,
    jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 0,
    adresse_rue: 'UA High School',
    ville: 'Musutafu',
    code_postal: '321-654',
    pays: 'Japon',
    acces_pmr: true,
    parking: true,
    equipements: ['Lits de récupération', 'Stock de bonbons', 'Défibrillateur Plus Ultra'],
    accepte_urgences: true,
    taux_remplissage: 1.0
  },
  {
    email: 'saitama@hero.med',
    password: await hash('password123', 10),
    prenom: 'Saitama',
    nom: 'Sensei',
    telephone: '0611111111',
    photo_url: '/img/professionel/saitama.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Préparation physique',
    sous_specialite: 'Renforcement musculaire extrême',
    diplomes_urls: ['self-training.pdf'],
    numero_adeli: '321654987',
    numero_rpps: '32165498701',
    consultation_type: [ConsultationType.PRESENTIEL],
    tarif_consultation: 50.00,
    statut_conventionnement: StatutConventionnement.NON_CONVENTIONNE,
    modes_reglement: [ModeReglement.ESPECES],
    carte_vitale: false,
    description: "Coach sportif minimaliste. Programme : 100 pompes, 100 squats, 100 abdos et 10km de course. TOUS LES JOURS !",
    experience_annees: 3,
    langues_parlees: ['Français', 'Japonais'],
    horaire_ouverture: '14:00',
    horaire_fermeture: '17:00',
    duree_consultation: 60,
    jours_travail: ['SAMEDI', 'DIMANCHE'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 30,
    adresse_rue: 'Z-City, Apt 666',
    ville: 'Z-City',
    code_postal: '666-666',
    pays: 'Japon',
    acces_pmr: false,
    parking: false,
    equipements: ['Zone d\'entraînement', 'Climatisation cassée', 'Manga'],
    accepte_urgences: false,
    taux_remplissage: 0.2
  },
  {
    email: 'sanji@baratie.med',
    password: await hash('password123', 10),
    prenom: 'Sanji',
    nom: 'Vinsmoke',
    telephone: '0622222222',
    photo_url: '/img/professionel/sanji.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Nutrition',
    sous_specialite: 'Cuisine thérapeutique',
    diplomes_urls: ['baratie-culinary.pdf', 'all-blue-research.pdf'],
    numero_adeli: '147258369',
    numero_rpps: '14725836901',
    consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.VISIO],
    tarif_consultation: 90.00,
    statut_conventionnement: StatutConventionnement.SECTEUR_1,
    modes_reglement: [ModeReglement.CB, ModeReglement.ESPECES],
    carte_vitale: true,
    description: "Expert en nutrition et cuisine thérapeutique. Attention : comportement différent selon le genre du patient.",
    experience_annees: 10,
    langues_parlees: ['Français', 'Anglais', 'Love'],
    horaire_ouverture: '11:00',
    horaire_fermeture: '23:00',
    duree_consultation: 40,
    jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 3,
    adresse_rue: 'Baratie Restaurant',
    ville: 'East Blue',
    code_postal: '11111',
    pays: 'Seas',
    acces_pmr: true,
    parking: false,
    equipements: ['Cuisine professionnelle', 'Jardin d\'herbes', 'Cave à vin médicinale'],
    accepte_urgences: true,
    taux_remplissage: 0.95
  },
  {
    email: 'tsunade@konoha.med',
    password: await hash('password123', 10),
    prenom: 'Tsunade',
    nom: 'Senju',
    telephone: '0633333333',
    photo_url: '/img/professionel/tsunade.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Chirurgie',
    sous_specialite: 'Ninjutsu médical',
    diplomes_urls: ['konoha-medical.pdf', 'hokage-certificate.pdf'],
    numero_adeli: '258369147',
    numero_rpps: '25836914701',
    consultation_type: [ConsultationType.PRESENTIEL],
    tarif_consultation: 200.00,
    statut_conventionnement: StatutConventionnement.SECTEUR_2,
    modes_reglement: [ModeReglement.CB, ModeReglement.ESPECES],
    carte_vitale: true,
    description: "Chirurgienne de génie et experte en médecine ninja. Possibilité de paris pendant la consultation (non remboursés).",
    experience_annees: 50,
    langues_parlees: ['Français', 'Japonais', 'Ninja'],
    horaire_ouverture: '10:00',
    horaire_fermeture: '16:00',
    duree_consultation: 30,
    jours_travail: ['LUNDI', 'MERCREDI', 'VENDREDI'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 14,
    adresse_rue: 'Tour de l\'Hokage',
    ville: 'Konoha',
    code_postal: '12345',
    pays: 'Pays du Feu',
    acces_pmr: true,
    parking: true,
    equipements: ['Bloc opératoire', 'Salle de régénération', 'Machine à sous'],
    accepte_urgences: true,
    taux_remplissage: 0.6
  },
  {
    email: 'zeno@dragon.med',
    password: await hash('password123', 10),
    prenom: 'Zeno',
    nom: 'Sama',
    telephone: '0644444444',
    photo_url: '/img/professionel/zeno.jpg',
    role: UserRole.MEDECIN,
    specialisation: 'Médecine universelle',
    sous_specialite: 'Manipulation temporelle',
    diplomes_urls: ['universe-7.pdf', 'all-universes.pdf'],
    numero_adeli: '369147258',
    numero_rpps: '36914725801',
    consultation_type: [ConsultationType.PRESENTIEL, ConsultationType.VISIO, ConsultationType.HYBRIDE],
    tarif_consultation: 1000.00,
    statut_conventionnement: StatutConventionnement.NON_CONVENTIONNE,
    modes_reglement: [ModeReglement.CB],
    carte_vitale: false,
    description: "Médecin omnipotent. Peut effacer l'univers en cas d'insatisfaction. Consultation sur recommandation divine uniquement.",
    experience_annees: 1000000,
    langues_parlees: ['Toutes'],
    horaire_ouverture: '00:00',
    horaire_fermeture: '23:59',
    duree_consultation: 1,
    jours_travail: ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI', 'DIMANCHE'],
    disponibilite: Disponibilite.DISPONIBLE,
    delai_rdv_moyen: 365,
    adresse_rue: 'Palais de Zeno',
    ville: 'Au-delà',
    code_postal: '00000',
    pays: 'Multivers',
    acces_pmr: true,
    parking: true,
    equipements: ['Bouton de destruction universelle', 'Salle temporelle', 'Gardes divins'],
    accepte_urgences: false,
    taux_remplissage: 0.1
  }
];

const patients = [
  {
    firstName: 'Bruce',
    lastName: 'Wayne',
    email: 'batman@wayne-enterprises.com',
    phone: '0666666666',
    profilePictureUrl: '/img/patient/batman.jpg',
    sport: 'Arts Martiaux',
    injury: 'Multiples fractures dues aux chutes de buildings',
    lastAppointment: new Date('2025-02-05'),
    nutritionalStatus: NutritionalStatus.GOOD,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Izuku',
    lastName: 'Midoriya',
    email: 'deku@ua.edu',
    phone: '0677777777',
    profilePictureUrl: '/img/patient/deku.jpg',
    sport: 'Super-Héroïsme',
    injury: 'Bras cassés à répétition (One For All)',
    lastAppointment: new Date('2025-02-04'),
    nutritionalStatus: NutritionalStatus.AVERAGE,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Son',
    lastName: 'Goku',
    email: 'goku@capsule-corp.com',
    phone: '0688888888',
    profilePictureUrl: '/img/patient/goku.jpg',
    sport: 'Arts Martiaux',
    injury: 'Surmenage dû aux entraînements à 100x la gravité',
    lastAppointment: new Date('2025-02-03'),
    nutritionalStatus: NutritionalStatus.GOOD,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Tony',
    lastName: 'Stark',
    email: 'tony@stark-industries.com',
    phone: '0699999999',
    profilePictureUrl: '/img/patient/ironman.jpg',
    sport: 'Vol en armure',
    injury: 'Problèmes cardiaques (réacteur ARK)',
    lastAppointment: new Date('2025-02-02'),
    nutritionalStatus: NutritionalStatus.CRITICAL,
    progressionStatus: ProgressionStatus.STAGNATING
  },
  {
    firstName: 'Monkey D.',
    lastName: 'Luffy',
    email: 'luffy@thousand-sunny.com',
    phone: '0611111111',
    profilePictureUrl: '/img/patient/luffy.jpg',
    sport: 'Piraterie',
    injury: 'Élongation excessive des membres (fruit du Gomu Gomu)',
    lastAppointment: new Date('2025-02-01'),
    nutritionalStatus: NutritionalStatus.GOOD,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Naruto',
    lastName: 'Uzumaki',
    email: 'naruto@konoha.gov',
    phone: '0622222222',
    profilePictureUrl: '/img/patient/naruto.jpg',
    sport: 'Ninjutsu',
    injury: 'Épuisement de chakra',
    lastAppointment: new Date('2025-01-31'),
    nutritionalStatus: NutritionalStatus.AVERAGE,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Saitama',
    lastName: 'Unknown',
    email: 'saitama@hero-association.org',
    phone: '0633333333',
    profilePictureUrl: '/img/patient/saitama.jpg',
    sport: 'Super-Héroïsme',
    injury: 'Dépression due à la facilité des combats',
    lastAppointment: new Date('2025-01-30'),
    nutritionalStatus: NutritionalStatus.GOOD,
    progressionStatus: ProgressionStatus.STAGNATING
  },
  {
    firstName: 'Peter',
    lastName: 'Parker',
    email: 'spidey@daily-bugle.com',
    phone: '0644444444',
    profilePictureUrl: '/img/patient/spiderman.jpg',
    sport: 'Acrobaties urbaines',
    injury: 'Tendinite aux poignets (lancer de toiles)',
    lastAppointment: new Date('2025-01-29'),
    nutritionalStatus: NutritionalStatus.AVERAGE,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Thor',
    lastName: 'Odinson',
    email: 'thor@asgard.realm',
    phone: '0655555555',
    profilePictureUrl: '/img/patient/thor.jpg',
    sport: 'Lancer de marteau',
    injury: 'Syndrome du canal carpien (Mjolnir)',
    lastAppointment: new Date('2025-01-28'),
    nutritionalStatus: NutritionalStatus.GOOD,
    progressionStatus: ProgressionStatus.IMPROVING
  },
  {
    firstName: 'Diana',
    lastName: 'Prince',
    email: 'wonder@themyscira.com',
    phone: '0666123456',
    profilePictureUrl: '/img/patient/wonderwoman.jpg',
    sport: 'Combat amazonien',
    injury: 'Tendinite à l\'épaule (lancer de lasso)',
    lastAppointment: new Date('2025-01-27'),
    nutritionalStatus: NutritionalStatus.GOOD,
    progressionStatus: ProgressionStatus.IMPROVING
  }
];

const healthProfessionals = [
  {
    firstName: 'Tony',
    lastName: 'Tony',
    email: 'chopper.nutritionist@tuatha.app',
    phone: '+33612345678',
    specialty: 'DOCTOR',
    licenseNumber: 'NUT123456',
    preferredContactMethod: 'EMAIL',
    availability: JSON.stringify({
      monday: ['9:00-12:00', '14:00-17:00'],
      tuesday: ['9:00-12:00', '14:00-17:00'],
      wednesday: ['9:00-12:00'],
      thursday: ['14:00-17:00'],
      friday: ['9:00-12:00', '14:00-17:00']
    })
  },
  {
    firstName: 'Tsunade',
    lastName: 'Senju',
    email: 'tsunade.dietitian@tuatha.app',
    phone: '+33623456789',
    specialty: 'DOCTOR',
    licenseNumber: 'DIT789012',
    preferredContactMethod: 'PHONE',
    availability: JSON.stringify({
      monday: ['10:00-18:00'],
      wednesday: ['10:00-18:00'],
      friday: ['10:00-18:00']
    })
  },
  {
    firstName: 'Sanji',
    lastName: 'Vinsmoke',
    email: 'sanji.nutritionist@tuatha.app',
    phone: '+33634567890',
    specialty: 'NUTRITIONIST',
    licenseNumber: 'NUT345678',
    preferredContactMethod: 'EMAIL',
    availability: JSON.stringify({
      tuesday: ['8:00-16:00'],
      thursday: ['8:00-16:00'],
      saturday: ['10:00-14:00']
    })
  },
  {
    firstName: 'Bruce',
    lastName: 'Banner',
    email: 'hulk.dietitian@tuatha.app',
    phone: '+33645678901',
    specialty: 'COACH',
    licenseNumber: 'DIT901234',
    preferredContactMethod: 'SMS',
    availability: JSON.stringify({
      monday: ['14:00-20:00'],
      wednesday: ['14:00-20:00'],
      friday: ['14:00-20:00']
    })
  }
];

const patientHealthTeams = [
  {
    patientId: 'pat-001',
    role: 'PRIMARY',
    startDate: new Date('2024-01-01'),
    notes: 'Suivi régulier pour optimisation des performances',
    lastContactDate: new Date('2024-02-01'),
    communicationPreference: 'EMAIL'
  },
  {
    patientId: 'pat-002',
    role: 'SECONDARY',
    startDate: new Date('2024-01-15'),
    notes: 'Programme de récupération post-traumatique',
    lastContactDate: new Date('2024-02-03'),
    communicationPreference: 'PHONE'
  },
  {
    patientId: 'pat-003',
    role: 'PRIMARY',
    startDate: new Date('2024-01-10'),
    notes: 'Suivi nutritionnel et performance',
    lastContactDate: new Date('2024-02-02'),
    communicationPreference: 'SMS'
  }
];

async function main() {
  console.log('Start seeding...');

  // Create professionals
  for (const professionnel of professionnels) {
    const user = await prisma.user.create({
      data: professionnel,
    });
    console.log(`Created user with id: ${user.id}`);
  }

  // Create patients
  for (const patient of patients) {
    const createdPatient = await prisma.patient.upsert({
      where: { email: patient.email },
      update: patient,
      create: patient,
    });
    console.log(`Created patient with id: ${createdPatient.id}`);
  }

  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
